import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/kagoya/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
mkdirSync('qa',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const errors=[], report={};
try{
  const page=await browser.newPage({viewport:{width:1440,height:1150}});
  page.on('pageerror',error=>errors.push(error.message));
  page.on('response',res=>{if(res.status()>=400)errors.push(`${res.status()} ${res.url()}`);});
  await page.goto('http://127.0.0.1:8765/');
  await page.locator('.word-item').last().waitFor();
  report.words=await page.locator('.word-item').count();
  report.hotspots=await page.locator('.hotspot').count();
  if(report.words!==11||report.hotspots!==11)throw new Error('Expected 11 words and hotspots');
  await page.locator('#play-ja').click();
  await page.waitForFunction(()=>document.getElementById('audio').currentTime>0);
  report.japanesePlayback=true;
  await page.locator('#choose-pt').click();
  await page.locator('.word-item[data-word="teacher"]').click();
  await page.waitForFunction(()=>document.getElementById('audio').currentTime>0 && document.getElementById('audio').src.includes('teacher-pt'));
  report.portuguesePlayback=true;
  await page.locator('#slow').click();
  report.slowRate=await page.locator('#audio').evaluate(el=>el.playbackRate);
  await page.locator('#zoom-in').click();
  report.zoom=await page.locator('#zoom-label').textContent();
  await page.locator('#zoom-reset').click();
  await page.locator('#show-original').click();
  if(!await page.locator('#original-dialog').evaluate(el=>el.open))throw new Error('Original dialog failed');
  await page.keyboard.press('Escape');
  await page.locator('.hotspot[data-word="chair"]').focus();
  await page.keyboard.press('Enter');
  if(await page.locator('#selected-ja').textContent()!=='いす')throw new Error('Keyboard selection failed');
  report.keyboard=true;
  report.media=await page.evaluate(async()=>{
    const results=[];
    for(const word of window.DICTIONARY)for(const lang of ['ja','pt']){
      const audio=new Audio(`audio/${word.id}-${lang}.mp3`);
      const duration=await new Promise((resolve,reject)=>{audio.addEventListener('loadedmetadata',()=>resolve(audio.duration),{once:true});audio.addEventListener('error',()=>reject(new Error(audio.src)),{once:true});audio.load();});
      if(!Number.isFinite(duration)||duration<.3)throw new Error('Invalid audio duration');results.push({id:word.id,lang,duration});
    }return results;
  });
  await page.screenshot({path:'qa/desktop.png',fullPage:true});
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
  mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://127.0.0.1:8765/');await mobile.locator('.word-item').last().waitFor();
  report.mobileOverflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(report.mobileOverflow)throw new Error('Mobile page overflows');
  await mobile.locator('.word-item[data-word="crayons"]').tap();
  await mobile.waitForFunction(()=>document.getElementById('audio').currentTime>0);
  report.mobileTap=await mobile.locator('#selected-ja').textContent();
  await mobile.locator('#zoom-in').tap();
  await mobile.locator('#zoom-in').tap();
  report.mobileZoom=await mobile.locator('#zoom-label').textContent();
  await mobile.locator('.word-item[data-word="teacher"]').tap();
  await mobile.locator('#zoom-reset').tap();
  await mobile.screenshot({path:'qa/mobile.png',fullPage:true});
  await mobile.setViewportSize({width:844,height:390});
  report.landscapeOverflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(report.landscapeOverflow)throw new Error('Landscape overflow');
  report.errors=errors;if(errors.length)throw new Error(errors.join('\n'));
  writeFileSync('qa/report.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
